################################################################################
# MQLib - storeRF
# MIT License
# Code to take random forests, as generated by the randomForest package, and
# store them in a file format that can then be used by the C++ code.
################################################################################

store.rf <- function(rf, filename) {
  # Size of each tree in the random forest
  sizes <- sapply(1:rf$forest$ntree, function(x) nrow(getTree(rf, x)))

  f <- file(filename, "w")
  
  # ntree nvar nnodes
  cat(paste0(rf$forest$ntree, " ", nrow(rf$importance), " ", sum(sizes),
             "\n"), file=f)
  
  # Start position of each tree (0-indexed)
  cat(paste0(paste(c(0, cumsum(head(sizes, -1))), collapse=" "), "\n"),
      file=f)
  
  # nnodes space-separated lines
  # Element 0: left daughter (0-indexed; -1 for none)
  # Element 1: right daughter (0-indexed; -1 for none)
  # Element 2: split variable (0-indexed; -1 for predict 0; -2 for predict 1)
  # Element 3: split point
  X <- do.call(rbind, lapply(1:rf$forest$ntree, function(x) {
  	tree <- getTree(rf, x)
    return(cbind(tree[,1]-1, tree[,2]-1,
                 ifelse(tree[,3] == 0, -tree[,6], tree[,3]-1), tree[,4]))
  }))
  write.table(X, file=f, row.names=F, col.names=F)
  close(f)
}